### ISSUE TITLE
1.6c (flipped screen) "A" SR ABCD outputs reversed

### ISSUE THREAD

**Issue by adrianfon9** [Chysn/O_C-HemisphereSuite#21] opened 2018-11-09 22:27 UTC
Should the behaviour look like this? 
Flipped: 
DCBA vs ABCD (Normal)?

Currently it still is outputting as if it were normal (not flipped) orientation.

Normal:
Out A: The most recent sample
Out B: n steps back
Out C: 2n steps back
Out D: 3n steps back

**Comment by Chysn** [comment] 2018-11-10 00:36
Hey, I’ll install flipped and review

**Comment by Chysn** [comment] 2018-11-10 02:52
I can confirm that the behavior is as expected in Hemisphere Suite 1.6C when the screen is flipped. Note that the names of the outputs will be reversed. That is, the physical output that normally functions as Out A will function as Out D in Flip 180 mode, etc.

**Comment by adrianfon9** [comment] 2018-11-10 02:58
Hi Chysn,

Thanks for the quick response. I just checked with 2 * “A”SR in linked mode (flipped screen) and it seems like  the right most out is the most recent stage and the left most is the last stage.

Is this functioning as intended?

Adrian

**Comment by Chysn** [comment] 2018-11-10 03:54
Do you have a way to post a video of what you’re doing? What you’re describing is not how it works for me.

**Comment by adrianfon9** [comment] 2018-11-11 02:33
Hi Chysn,

I hope this video makes sense:
https://youtu.be/E3wAlZgpRmY

I plugged an LFO into the LEFT most CV (D flipped) and a trigger in the LEFT most TRIG (D flipped).

It seems like out C outputs index 0 and out D outputs index 1. I would expect the opposite to occur. I flip back and forth and try to indicate with my hands (poorly? sorry haha) the index number that i am seeing.

Adrian

**Comment by Chysn** [comment] 2018-11-11 03:40
OK, thank you, that's very helpful.

I've got a uO_C coming this week, and I think that will make it easier for me to review this.

**Comment by adrianfon9** [comment] 2018-11-13 15:37
Hi Chysn,

Just thought I’d follow up on this. And also to perhaps request a few features?
- if index is changed through cv, can we see this update on the app? (currently static @ encoder setting)

After some further tests I have some questions on the method the ASR functions.

It seems like it will quantize items coming from the right side and shift everything to the left by the assigned trigger.

is the out A and B tap assigned starting from the right? or the left? The reason i ask, is if i adjust my source LFO, the shift register will not respond for a number of steps (or shifts). In other words, the shift register seems to hold in memory as intended the CV shape, but doesn’t read from it until some time. I would expect the index to be from the right.

e.g.

CV sequence{index: value}: {0: 0.25, 1: 0.35, 2: 0.45, 3: 0.55}

Expected Behaviour:
sequence == (1, 0.35)
 ASR index @ 0 is 0.35
 ASR index @ 1 is 0.25

Adrian

**Comment by Chysn** [comment] 2018-11-27 22:49
If you're using both hemispheres with "A"SR, the A output (leftmost) is the most recent sample. The B output is the sample 1 x index before that. The C output is the sample 2 x index before the most recent. The D output (rightmost) is the sample 3 x index before the most recent. I guess you could say that the signal moves from left to right. The signal that's in A right now will be in B in {index} clocks.

I tested this with flipped screen on my µO_C, and it behaves as expected.

I think it's a good idea to indicate the effect of CV on the index.

**Comment by Chysn** [comment] 2018-12-05 15:40
Closing because it appears to be working as expected in v1.7

**Closed by Chysn** 2018-12-05 15:40 UTC
