### ISSUE TITLE
1.6b (Flipped Screen) Clock Div top selection does not function on left side

### ISSUE THREAD

**Issue by adrianfon9** [Chysn/O_C-HemisphereSuite#18] opened 2018-11-06 22:19 UTC
Clock Div top selection does not function on left side

**Comment by Chysn** [comment] 2018-11-06 22:48
Duplicate of #16 (same root cause), so closing. This will be addressed with the 1.6C release on Nov. 9.

**Closed by Chysn** 2018-11-06 22:48 UTC
Labels: bug, duplicate
